apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cert-manager
resources:
  - acme.cert-manager.io_challenges.yaml
  - acme.cert-manager.io_orders.yaml
  - cert-manager.io_certificaterequests.yaml
  - cert-manager.io_certificates.yaml
  - cert-manager.io_clusterissuers.yaml
  - cert-manager.io_issuers.yaml
